sales_analytics:
  outputs:
    dev:
      dataset: sales_analytics_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: ent-data-warehouse-dev
      threads: 2
      type: bigquery
  target: dev
